### ISSUE TITLE
RWTH isn't mentioned either on the home or about page

### ISSUE THREAD

**Issue by clonejo** [lernranz/lernranz#1]

**Comment by Mimoja** [comment]
I made 2 ribbons. Maybe you like them
Could look like this:
![site](https://cloud.githubusercontent.com/assets/10907336/8720942/8062d4f2-2bb6-11e5-81a8-59d8af146b3c.png)

![github](https://cloud.githubusercontent.com/assets/10907336/8720940/805f3be4-2bb6-11e5-9a00-aec1af651726.png)
![rwth](https://cloud.githubusercontent.com/assets/10907336/8720941/80604606-2bb6-11e5-903c-b90018c5fdd6.png)

**Comment by clonejo** [comment]
These look fancy, but I would not use the RWTH's logo on the site, as the university would have to approve on that.

Also I'd rather keep the height of the header low to save space. I think [Font Awesome](http://fontawesome.io/icons/) fulfills most of our icon needs.

**Comment by Mimoja** [comment]
As it is clearly mentioned, that this project is not related to anything with the RWTH, we could simply ask for the permission to use the Logo for a Link. 

OT: Maybe a link to the IT-Center would be more appropriate?

**Comment by clonejo** [comment]
The IT Center is referred to on the about page. I think I'll just add “für Studenten der RWTH Aachen” to the header.
